name: CI
on: push
jobs:
  prod-check: 
    if: ${{ github.ref == 'refs/heads/master' }} 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"

{
  "event_type": "test-event",
  "client_payload": {
     "data": 123
  }
}
